=== kelvinBen/ei/workflow/dtd/taskListCustomize.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="customize">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" minOccurs="0" ref="task-header"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="item">
        <xsd:complexType>
            <xsd:attribute name="field-id" type="xsd:string" use="optional"/>
            <xsd:attribute name="index" type="xsd:string" use="optional"/>
            <xsd:attribute name="html-style" type="xsd:string" use="optional"/>
            <xsd:attribute name="isReserved" type="xsd:string" use="optional" default="TRUE"/>
            <xsd:attribute name="title" type="xsd:string" use="optional"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="task-header">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" minOccurs="0" ref="item"/>
            </xsd:sequence>
            <xsd:attribute name="classify" type="xsd:string" use="optional"/>
            <xsd:attribute name="process-id" type="xsd:string" use="optional"/>
            <xsd:attribute name="type" type="xsd:string" use="optional"/>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== kelvinBen/ei/src/main/resources/config/taskListCustomize.xml
<?xml version="1.0" encoding="UTF-8"?>
<customize xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../dtd/taskListCustomize.xsd">
  <task-header classify="ExampleMeeting" type="PROCESSTYPE">
    <item field-id="SUBJECT" index="0" isReserved="true" title="标题"/>
  </task-header>
  <task-header classify="daily" type="PROCESSTYPE">
    <item field-id="SUBJECT" index="0" isReserved="true" title="标题"/>
  </task-header>
  <task-header classify="EDOC" process-id="" type="PROCESSTYPE">
    <item field-id="SUBJECT" html-style="" index="1" isReserved="true" title="标题"/>
    <item field-id="EDOC_TYPE" html-style="" index="2" isReserved="true" title="公文种类"/>
    <item field-id="SECRET_LEVEL" html-style="" index="3"
      isReserved="true" title="秘密等级"/>
    <item field-id="KEEP_SECRET_TIME" html-style="" index="4"
      isReserved="true" title="标题"/>
    <item field-id="INSTANT_LEVEL" html-style="" index="5"
      isReserved="true" title="紧急程度"/>
    <item field-id="CREATE_ORGAN" html-style="" index="6"
      isReserved="true" title="发文机关"/>
    <item field-id="WORD_NUMBER" html-style="" index="7"
      isReserved="true" title="发文字号"/>
    <item field-id="MAIN_SEND_ORGAN" html-style="" index="8"
      isReserved="true" title="主送机关"/>
    <item field-id="APPROVE_DATE" html-style="" index="9"
      isReserved="true" title="成文日期"/>
    <item field-id="COPY_SEND_ORGAN" html-style="" index="10"
      isReserved="true" title="抄送机关"/>
    <item field-id="OUTER_SEND_ORGAN" html-style="" index="11"
      isReserved="true" title="外发机关"/>
    <item field-id="CREATE_DATE" html-style="" index="12"
      isReserved="true" title="草拟时间"/>
    <item field-id="APPROVE_USER_ID" html-style="" index="13"
      isReserved="true" title="签发领导"/>
  </task-header>
</customize>
