=== kelvinBen/ei/workflow/dtd/WfDSystemConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             targetNamespace="http://WfDSystemConfig.config.wfdefinition.mast.org"
		     xmlns="http://WfDSystemConfig.config.wfdefinition.mast.org"
		     elementFormDefault="qualified">
    <xsd:element name="auto-task">
        <xsd:annotation>
            <xsd:documentation>系统自动任务,一般分配到各个环节执行</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" minOccurs="1" ref="task"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="condition">
        <xsd:annotation>
            <xsd:documentation>属性:id 条件id ,name 条件名称</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="xsd:string">
                    <xsd:attribute name="id" type="xsd:string" use="optional"/>
                    <xsd:attribute name="name" type="xsd:string" use="optional"/>
                    <xsd:attribute name="description" type="xsd:string" use="optional"/> 
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="system-condition">
        <xsd:annotation>
            <xsd:documentation>系统内置的操作条件,一般作为环节操作条件</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" minOccurs="1" ref="condition"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="system-config">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="auto-task" minOccurs="0" maxOccurs="1"/>
                <xsd:element ref="system-condition" minOccurs="0" maxOccurs="1"/>
                <xsd:element ref="limit" minOccurs="0" maxOccurs="1"/>
                <xsd:element ref="adjunct-right" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="participant-option" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="trans-event" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="enumerates" minOccurs="0" maxOccurs="1"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="task">
        <xsd:annotation>
            <xsd:documentation>属性:id 任务id,name 任务名称,task-class
                任务执行类,description 任务说明,flow-type流程类型</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:attribute name="description" type="xsd:string" use="optional"/>
            <xsd:attribute name="id" type="xsd:string" use="optional"/>
            <xsd:attribute name="name" type="xsd:string" use="optional"/>
            <xsd:attribute name="task-class" type="xsd:string" use="optional"/>
            <xsd:attribute name="flow-type" type="xsd:string" use="optional"/>
            <xsd:attribute name="Execution" use="optional" default="SYNCHR"> 
            	<xsd:simpleType>
             		<xsd:restriction base="xsd:NMTOKEN">
                  		<xsd:enumeration value="ASYNCHR"/>
                  		<xsd:enumeration value="SYNCHR"/>
               		</xsd:restriction>            	
            	</xsd:simpleType> 
            </xsd:attribute>            
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="limit">
        <xsd:annotation>
            <xsd:documentation>流程、环节超时限制配置选项</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" minOccurs="0" ref="agent"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="agent">
        <xsd:annotation>
            <xsd:documentation>属性:id 限制id,name 限制名称,agent-class
                代理执行类,flow-type 流程类型，description 限制说明</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:attribute name="description" type="xsd:string" use="optional"/>
            <xsd:attribute name="id" type="xsd:string" use="optional"/>
            <xsd:attribute name="name" type="xsd:string" use="optional"/>
            <xsd:attribute name="agent-class" type="xsd:string" use="optional"/>
            <xsd:attribute name="flow-type" type="xsd:string" use="optional"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="adjunct-right">
        <xsd:annotation>
            <xsd:documentation>流程附件(例如：word正文)权限配置项</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" minOccurs="1" ref="tab"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="tab">
        <xsd:annotation>
            <xsd:documentation>tab标签，用来标示一类选项</xsd:documentation>
            <xsd:documentation>align排列：horizontal水平，Vertical垂直</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" minOccurs="0" ref="option"/>
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:string" use="required"/>
            <xsd:attribute name="title" type="xsd:string" use="optional"/>
            <xsd:attribute name="flow-type" type="xsd:string" use="optional"/>
            <xsd:attribute name="align" use="optional"> 
            	<xsd:simpleType>
             		<xsd:restriction base="xsd:NMTOKEN">
                  		<xsd:enumeration value="horizontal"/>
                  		<xsd:enumeration value="Vertical"/>
               		</xsd:restriction>            	
            	</xsd:simpleType> 
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="option">
        <xsd:annotation>
            <xsd:documentation>枚举选项</xsd:documentation>
            <xsd:documentation>key对应流程相关信息中的正文权限扩展属性</xsd:documentation>
            <xsd:documentation>type展现类型，radio单选按钮，checkbox复选按钮，label标签</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
            	<xsd:element maxOccurs="unbounded" minOccurs="0" ref="enum-group"/>
                <xsd:element maxOccurs="unbounded" minOccurs="0" ref="enum-value"/>
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:string" use="required"/>
            <xsd:attribute name="title" type="xsd:string" use="optional"/>
            <xsd:attribute name="key" type="xsd:string" use="optional"/>
            <xsd:attribute name="type" use="required">
            	<xsd:simpleType>
             		<xsd:restriction base="xsd:NMTOKEN">
                  		<xsd:enumeration value="radio"/>
                  		<xsd:enumeration value="checkbox"/>
                  		<xsd:enumeration value="label"/>
               		</xsd:restriction>            	
            	</xsd:simpleType> 
            </xsd:attribute>   
            <xsd:attribute name="align" use="optional"> 
            	<xsd:simpleType>
             		<xsd:restriction base="xsd:NMTOKEN">
                  		<xsd:enumeration value="horizontal"/>
                  		<xsd:enumeration value="Vertical"/>
               		</xsd:restriction>            	
            	</xsd:simpleType> 
            </xsd:attribute>  
			<xsd:attribute name="isdefault" type="xsd:string" use="optional" default="false"/>                  
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="enum-group">
        <xsd:annotation>
            <xsd:documentation>选项值分组</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" minOccurs="1" ref="enum-value"/>
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:string" use="required"/>
            <xsd:attribute name="title" type="xsd:string" use="optional"/>  
            <xsd:attribute name="align" use="optional"> 
            	<xsd:simpleType>
             		<xsd:restriction base="xsd:NMTOKEN">
                  		<xsd:enumeration value="horizontal"/>
                  		<xsd:enumeration value="Vertical"/>
               		</xsd:restriction>            	
            	</xsd:simpleType> 
            </xsd:attribute>                        
        </xsd:complexType>
    </xsd:element>    
    <xsd:element name="enum-value">
        <xsd:annotation>
            <xsd:documentation>一般选项</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:attribute name="id" type="xsd:string" use="required"/>
            <xsd:attribute name="title" type="xsd:string" use="optional"/>
            <xsd:attribute name="key" type="xsd:string" use="optional"/>
            <xsd:attribute name="type" use="optional">
            	<xsd:simpleType>
             		<xsd:restriction base="xsd:NMTOKEN">
                  		<xsd:enumeration value="radio"/>
                  		<xsd:enumeration value="checkbox"/>
               		</xsd:restriction>            	
            	</xsd:simpleType> 
            </xsd:attribute>  
            <xsd:attribute name="isdefault" type="xsd:string" use="optional"/>          	
        </xsd:complexType>
    </xsd:element>
	
    <xsd:element name="participant-option">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" minOccurs="1" ref="select-item">
                	<xsd:annotation>
                		<xsd:documentation>参与者选择项配置,包括组织机构、历史环节参与者、业务模块等相关配置</xsd:documentation>
                	</xsd:annotation>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>	
	<xsd:element name="select-item">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" minOccurs="1" ref="select-type">
					<xsd:annotation>
						<xsd:documentation>选择项对应的选择类型</xsd:documentation>
					</xsd:annotation>
				</xsd:element>				
			</xsd:sequence>			
			<xsd:attribute name="key" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>关键值</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="display-name" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>选择项显示名称</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="radio-url" type="xsd:string" use="optional">
				<xsd:annotation>
					<xsd:documentation>单选url</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="checkbox-url" type="xsd:string" use="optional">
				<xsd:annotation>
					<xsd:documentation>多选url</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>						
            <xsd:attribute name="use-mode" use="required">
				<xsd:annotation>
					<xsd:documentation>用途,组织机构\历史环节参与者\业务模块等</xsd:documentation>
				</xsd:annotation>
            	<xsd:simpleType>
             		<xsd:restriction base="xsd:NMTOKEN">
                  		<xsd:enumeration value="organization"/>
                  		<xsd:enumeration value="historyact"/>
						<xsd:enumeration value="formconfig"/>
					</xsd:restriction>            	
            	</xsd:simpleType> 
            </xsd:attribute>  								
		</xsd:complexType>
	</xsd:element>	
	<xsd:element name="select-type">
		<xsd:complexType>
			<xsd:attribute name="key" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>关键值</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="name" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>类型名称</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="select-url" type="xsd:string" use="optional">
				<xsd:annotation>
					<xsd:documentation>值选择界面的URL地址，用于选择具体数据,如果不填,则根据radio-url、checkbox-url来确定</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>	
            <xsd:attribute name="select-type" use="optional">
				<xsd:annotation>
					<xsd:documentation>选择类型，单选或多选</xsd:documentation>
				</xsd:annotation>
            	<xsd:simpleType>
             		<xsd:restriction base="xsd:NMTOKEN">
                  		<xsd:enumeration value="radio"/>
                  		<xsd:enumeration value="checkbox"/>
						<xsd:enumeration value="text"/>
					</xsd:restriction>            	
            	</xsd:simpleType> 
            </xsd:attribute>  							
		</xsd:complexType>
	</xsd:element>		
		
    <xsd:element name="trans-event">
        <xsd:annotation>
            <xsd:documentation>迁移事件执行类配置</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" minOccurs="0" ref="event"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="event">
        <xsd:annotation>
            <xsd:documentation>属性:id 限制id,name 限制名称,agent-class
                代理执行类,flow-type 流程类型，description 限制说明</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:attribute name="description" type="xsd:string" use="optional"/>
            <xsd:attribute name="id" type="xsd:string" use="optional"/>
            <xsd:attribute name="name" type="xsd:string" use="optional"/>
            <xsd:attribute name="execution" type="xsd:string" use="optional"/>
            <xsd:attribute name="flow-type" type="xsd:string" use="optional"/>
        </xsd:complexType>
    </xsd:element>	
	
    <xsd:element name="enumerates">
        <xsd:annotation>
            <xsd:documentation>系统枚举类型配置，包括：流程监控者角色、环节参与者接受方式等</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" minOccurs="0" ref="enumerate"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="enumerate">
        <xsd:annotation>
            <xsd:documentation>枚举类型</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" minOccurs="0" ref="enum-item"/>
            </xsd:sequence>
            <xsd:attribute name="description" type="xsd:string" use="optional"/>
            <xsd:attribute name="id" type="xsd:string" use="optional"/>
            <xsd:attribute name="name" type="xsd:string" use="optional"/>	
			<xsd:attribute name="flow-type" type="xsd:string" use="optional"/>		
        </xsd:complexType>
    </xsd:element>	
    <xsd:element name="enum-item">
        <xsd:annotation>
            <xsd:documentation>属性:id ,name 类型名称,description 类型描述</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:attribute name="description" type="xsd:string" use="optional"/>
            <xsd:attribute name="id" type="xsd:string" use="optional"/>
            <xsd:attribute name="name" type="xsd:string" use="optional"/>
        </xsd:complexType>
    </xsd:element>		
</xsd:schema>

=== kelvinBen/ei/WebContent/WEB-INF/classes/config/WfDSystemConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<system-config xmlns="http://WfDSystemConfig.config.wfdefinition.loushang.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://WfDSystemConfig.config.wfdefinition.loushang.org WfDSystemConfig.xsd ">
	<!--系统自动任务,一般分配到各个环节执行-->
	<auto-task>
	<!--属性:id 任务id,name 任务名称,task-class 任务执行类,description 任务说明-->
		<!--<task id="testTaskApprove" name="审批通过" task-class="net.mast.workflow.test.TaskApprove" flow-type="" description=""/>
		<task id="testTaskReject"  name="审批驳回" task-class="net.mast.workflow.test.TaskReject" flow-type="" description=""/>
	  	 <task id="examplemeeting"  name="修改会议状态" task-class="bpmexample.meeting.ChangeState" flow-type="" description=""/> -->
		
		<!-- 主流程使用:在主流程中启动子流程,异步 -->
		<task id="StartSubProcWait" name="启动子流程异步" 
		task-class="net.mast.workflow.subProcess.StartSubProcAyn" flow-type="" description="" Execution="ASYNCHR"/>
		
		<!-- 主流程使用:在主流程中启动子流程,异步 
		<task id="StartSubProcAynCommon" name="启动子流程异步通用" 
		task-class="net.mast.workflow.subProcess.StartSubProcAynCommon" flow-type="" description="" Execution="ASYNCHR"/>-->
		
		<!-- 主流程使用:流程定义在隐藏域中,异步 
		<task id="StartSubProcAynFromHidden" name="用隐藏域数据启动子流程异步" 
		task-class="net.mast.workflow.subProcess.StartSubProcAynFromHidden" flow-type="" description="" Execution="ASYNCHR"/>-->
		
		<!-- 主流程使用:流程定义和创建者在隐藏域中,异步 
		<task id="StartSubProcAynFromHidden_Proc_UserId" name="用隐藏流程定义和创建者启动子流程异步" 
		task-class="net.mast.workflow.subProcess.StartSubProcAynFromHidden_Proc_UserId" flow-type="" description="" Execution="ASYNCHR"/>-->
		
		<!-- 主流程使用:流程定义在相关参数中,异步 
		<task id="StartSubProcAynFromParas" name="用相关数据启动子流程异步" 
		task-class="net.mast.workflow.subProcess.StartSubProcAynFromParas" flow-type="" description="" Execution="ASYNCHR"/>-->
		
		<!-- 主流程使用:在主流程中启动子流程,同步 -->
		<task id="StartSubProcNoWait" name="启动子流程同步" 
		task-class="net.mast.workflow.subProcess.StartSubProcSyn" flow-type="" description=""/>
		
		<!-- 主流程使用:在主流程中启动子流程,同步 
		<task id="StartSubProcSynCommon" name="启动子流程同步通用"
		task-class="net.mast.workflow.subProcess.StartSubProcSynCommon" flow-type="" description=""/>-->
		
		<!-- 主流程使用:通过获取流程定义时的相关参数中的流程定义,创建子流程,创建者仍然从表单上面取,遵循表单的字段定义,同步 
		<task id="StartSubProcAynFromParas" name="用相关数据启动子流程同步"
		task-class="net.mast.workflow.subProcess.StartSubProcSynFromParas" flow-type="" description=""/>-->
		
		<!-- 主流程使用:通过表单的隐藏域获取子流程定义ID,同步 
		<task id="StartSubProcSynFormHidden" name="用隐藏域数据启动子流程同步"
		task-class="net.mast.workflow.subProcess.StartSubProcSynFromHidden" flow-type="" description=""/>-->
		
		<!-- 主流程使用:通过表单的隐藏域获取子流程定义ID和创建者ID,同步 
		<task id="StartSubProcSynFromHidden_Proc_UserId" name="用隐藏流程定义和创建者启动子流程同步"
		task-class="net.mast.workflow.subProcess.StartSubProcSynFromHidden_Proc_UserId" flow-type="" description=""/>-->
		
		<!-- 子流程使用:启动并返回数据给主流程,配合启动子流程异步使用 -->
		<task id="Start_ReturnDataToMainProc" name="启动并返回数据给主流程" 
		task-class="net.mast.workflow.subProcess.Start_ReturnDataToMainProc" flow-type="" description=""/>
		
		<!-- 子流程使用:返回子流程数据给主流程,根据保留域交换数据,配合同步启动子流程使用 
		<task id="ReturnDataToMainProc" name="返回数据给主流程" 
		task-class="net.mast.workflow.subProcess.ReturnDataToMainProc" flow-type="" description=""/>-->
		
		<!-- 子流程使用:根据表单上的域名来交换数据 -->
		<task id="ReturnDataByFieldName" name="根据域名交换数据"
		task-class="net.mast.workflow.subProcess.ReturnDataByFieldName" flow-type="" description=""/>

		<task id="forTest" name="环节自动任务测试" task-class="net.mast.workflow.test.TestTask" flow-type="" description=""/>

		 		
 	</auto-task>	
	<!--系统内置的操作条件,一般作为环节操作条件-->
	<system-condition>
	<!--属性:id 条件id ,name 条件名称,expression 条件表达式-->
		<condition id="isNewDOc" name="新文档" >
		<![CDATA[ (field_DATAID==null || "".equals(field_DATAID)) ]]>
		</condition>
		<condition id="isNewDOc" name="非新文档" >
		<![CDATA[ !(field_DATAID==null || "".equals(field_DATAID)) ]]>
		</condition>		
		<condition id="curParty" name="当前处理人">
		 <![CDATA[ (activityUser.contains(curUser)) ]]>
		</condition>
		<condition id="curParty" name="非当前处理人">
		 <![CDATA[ !(activityUser.contains(curUser)) ]]>
		</condition>
		<condition id="huiqian" name="会签" >
		<![CDATA[ (isMulti.booleanValue()) ]]>
		</condition>
		<condition id="lastHuiqian" name="最后会签人">
			<![CDATA[ (taskCount.intValue()==1) ]]>
		</condition>			
		<condition id="notlastHuiqian" name="非最后会签人">
			<![CDATA[ (taskCount.intValue()>1) ]]>
		</condition>				
		<condition id="huiqian" name="非会签" >
		<![CDATA[ !(isMulti.booleanValue()) ]]>
		</condition>
		<condition id="response" name="监控者" >
		<![CDATA[ (activityResponsibleUser.contains(curUser)) ]]>
		</condition>
		<condition id="response" name="非监控者" >
		<![CDATA[ !(activityResponsibleUser.contains(curUser)) ]]>
		</condition>	
		<condition id="history" name="历史参与者" >
		<![CDATA[ (processHistoryUser.contains(curUser)) ]]>
		</condition>
		<condition id="history" name="非历史参与者" >
		<![CDATA[ !(processHistoryUser.contains(curUser)) ]]>
		</condition>
		<condition id="sendUser" name="发送人" >
		<![CDATA[ (previousUserIds.contains(curUser)) ]]>
		</condition>
		<condition id="notSendUser" name="非发送人" >
		<![CDATA[ !(previousUserIds.contains(curUser)) ]]>
		</condition>
<!--	<condition id="read" name="已读" >
		<![CDATA[ ("1".equals(docReadFlag)) ]]>
		</condition>
		<condition id="notRead" name="未读" >
		<![CDATA[ (docReadFlag==null || "".equals(field_DATAID) || "0".equals(field_DATAID)) ]]>
		</condition>
-->
		<condition id="open.running" name="运行状态">
			<![CDATA[ ("open.running".equals(proCurrentState)) ]]>
		</condition>
		<condition id="open.not_running" name="未运行状态">
			<![CDATA[ ("open.not_running".equals(proCurrentState)) ]]>
		</condition>
<!--
		<condition id="open.not_running.not_started" name="未开始状态">
			<![CDATA[ ("open.not_running.not_started".equals(proCurrentState)) ]]>
		</condition>
-->
		<condition id="open.not_running.suspended" name="挂起">
			<![CDATA[ ("open.not_running.suspended".equals(proCurrentState)) ]]>
		</condition>
		<condition id="closed.completed" name="结束">
			<![CDATA[ ("closed.completed".equals(proCurrentState)) ]]>
		</condition>
<!--
		<condition id="closed.terminated" name="强制结束">
			<![CDATA[ ("closed.terminated".equals(proCurrentState)) ]]>
		</condition>
		<condition id="closed.aborted" name="取消">
			<![CDATA[ ("closed.aborted".equals(proCurrentState)) ]]>
		</condition>		
-->
		<condition id="read_only" name="只读">
			<![CDATA[(!activityUser.contains(curUser) && !"".equals(DATAID_field)) || readOnlyFieldList.contains("${name}") || isLocked.booleanValue()]]>
		</condition>					
	</system-condition>
	<!--流程、环节时间限制-->
	<limit>
	<!--属性:id 限制id,name 限制名称,agent-class 代理执行类,flow-type 流程类型，description 限制说明-->
		<agent id="limit" name="限时提醒" agent-class="net.mast.workflow.wfclient.taskinfo.limit.CommonLimitAgent" flow-type="" description="" />
		<agent id="warn" name="警告提醒" agent-class="net.mast.workflow.wfclient.taskinfo.limit.CommonWarnLimitAgent" flow-type="" description="" />
		<agent id="submit" name="自动提交" agent-class="net.mast.workflow.wfclient.taskinfo.limit.CommonSubmitLimitAgent" flow-type="" description="该选项适用于不需要选择的任务发送方式" />		
	</limit>
	<!--流程附件(例如：word正文)权限配置项-->
	<adjunct-right>
		<tab id="docRright" title="编辑权限" flow-type="" align="horizontal">
			<option id="edit" title="可编辑" key="documentRight" type="radio" align="horizontal" >
				<enum-group id="emendRight" title="修订权限" align="Vertical">
					<enum-value id="true" title="显示修订" key="emendRight" type="radio"/>
					<enum-value id="hidden" title="隐藏修订" key="emendRight" type="radio"/>
					<enum-value id="false" title="保持不变" key="emendRight" type="radio"/>
				</enum-group>	
			</option>
			<option id="read" title="可浏览" key="documentRight" type="radio" align="horizontal" isdefault="true">
				<enum-group id="emendRight" title="修订权限" align="Vertical">
					<enum-value id="true" title="显示修订" key="emendRight" type="radio" isdefault="true"/>
					<enum-value id="hidden" title="隐藏修订" key="emendRight" type="radio"/>
					<enum-value id="false" title="保持不变" key="emendRight" type="radio"/>
				</enum-group>
			</option>	
			<option id="emend" title="可修订" key="documentRight" type="radio" align="horizontal">
				<enum-group id="emendRight" title="修订权限" align="Vertical">
					<enum-value id="true" title="用户可以接受修订" key="emendRight" type="radio"/>
					<enum-value id="false" title="用户不能接受修订" key="emendRight" type="radio"/>
				</enum-group>			
			</option>										
		</tab>
		<tab id="accessRright" title="存取权限" flow-type=""   align="horizontal">
			<option id="docLocalOpen" title="是否有本地文件导入的权限" type="label" align="horizontal">
				<enum-value id="true" title="有" key="docLocalOpen" type="radio"/>
				<enum-value id="false" title="没有" key="docLocalOpen" type="radio"/>
			</option>
			<option id="docLocalSave" title="是否能另存为本地文件" type="label" align="horizontal">
				<enum-value id="true" title="能" key="docLocalSave" type="radio"/>
				<enum-value id="false" title="不能" key="docLocalSave" type="radio"/>
			</option>			
		</tab>	
		<tab id="sealRright" title="盖章权限" flow-type=""  align="horizontal">
			<option id="docSeal" title="是否可以盖章" type="label" align="horizontal">
				<enum-value id="true" title="是" key="docSeal" type="radio"/>
				<enum-value id="false" title="否" key="docSeal" type="radio"/>
			</option>
			<option id="docProtectSeal" title="是否保护印章" type="label" align="horizontal">
				<enum-value id="true" title="保护" key="docProtectSeal" type="radio"/>
				<enum-value id="false" title="不保护" key="docProtectSeal" type="radio"/>
			</option>			
		</tab>	
		<tab id="signRight" title="批注权限" flow-type=""  align="horizontal">
			<option id="docSign" title="是否全文批注" type="label" align="horizontal">
				<enum-value id="true" title="是" key="docSign" type="radio"/>
				<enum-value id="false" title="否" key="docSign" type="radio"/>
			</option>
			<option id="docSignClear" title="全文批注是否清稿" type="label" align="horizontal"> 
				<enum-value id="true" title="是" key="docSignClear" type="radio"/>
