=== kelvinBen/ei/WebContent/WEB-INF/classes/dtd/ClassesConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" attributeFormDefault="qualified">
    <xsd:element name="classes">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" minOccurs="1" ref="cinterface"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="cimplement">
        <xsd:complexType>
        	<xsd:sequence>
        		<xsd:element minOccurs="0" maxOccurs="unbounded" ref="init-parameter"></xsd:element>
        	</xsd:sequence>
            <xsd:attribute name="name" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="init-parameter" >
        <xsd:complexType mixed="true">
            <xsd:attribute name="name" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="cinterface">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" minOccurs="1" ref="cimplement"/>
            </xsd:sequence>
            <xsd:attribute name="name" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== kelvinBen/ei/workflow/config/ClassesConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<classes xsi:noNamespaceSchemaLocation="../dtd/ClassesConfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<cinterface name="com.ntmast.workform.manager.database.DatabaseAccessObject">
		<!-- 应用服务器weblogic + 数据库oracle 10G 采用的实现 -->
		<!-- 
			<cimplement name="net.mast.workform.database.weblogic.oracle.DatabaseAccessObjectImpl_weblogic_oracle"></cimplement> 
		-->
		<!---->
		<cimplement name="net.mast.workform.database.DatabaseAccessObjectImpl" />
		
	</cinterface>
	<cinterface name="com.ntmast.workform.manager.filter.FormFilter">
		
		<cimplement name="com.ntmast.workform.manager.filter.DefaultOrganizeFilter">
			<init-parameter name="FilteParameterName">organize-id</init-parameter>
		</cimplement>
		
		<cimplement name="com.ntmast.workform.manager.filter.ProcessTypeFilter">
			<init-parameter name="FilteTypeName">process-type</init-parameter>
		</cimplement>
		
	</cinterface>
	<cinterface name="com.ntmast.workform.manager.iforms.FormManager">
		<!--<cimplement name="com.ntmast.workform.manager.formimps.FormManagerForFile"/>-->
		<cimplement name="com.ntmast.workform.manager.formimps.FormManagerForDB"/>
	</cinterface>
	<cinterface name="com.ntmast.workform.manager.iforms.FormTemplate">
		<!--<cimplement name="com.ntmast.workform.manager.formimps.FormTemplateForFile"/>-->
		<cimplement name="com.ntmast.workform.manager.formimps.FormTemplateForDB"/>
	</cinterface>
	<cinterface name="com.ntmast.workform.manager.iforms.FormDataManager">
		<cimplement name="com.ntmast.workform.manager.formimps.FormDataManagerImp"/>
	</cinterface>
	<cinterface name="com.ntmast.workform.manager.iforms.AdjunctWriter">
		<cimplement name="com.ntmast.workform.manager.formimps.AdjunctWriterForDatabase"/>
<!--		<cimplement name="com.ntmast.workform.manager.formimps.AdjunctWriterForFile">
			<init-parameter name="RootPath">D:/WUTemp</init-parameter>
		</cimplement>-->
	</cinterface>
	<cinterface name="com.ntmast.workform.manager.iforms.TempletWriter">
		<cimplement name="com.ntmast.workform.manager.formimps.TempletWriterForDatabase"/>
<!--		<cimplement name="com.ntmast.workform.manager.formimps.TempletWriterForFile">
			<init-parameter name="RootPath">D:/WUTemp</init-parameter>
		</cimplement>-->
	</cinterface>
	<cinterface name="com.ntmast.workform.manager.renderer.Dictionary">
		<cimplement name="net.mast.workform.renderer.DictionaryImp"/>
	</cinterface>
	<cinterface name="com.ntmast.workform.manager.renderer.Security">
		<cimplement name="net.mast.workform.renderer.SecurityImp"/>
	</cinterface>
	<cinterface name="com.ntmast.processmanage.ProcessAccessor">
		<!--<cimplement name="com.ntmast.processmanage.ProcessAccessorForFile"/>-->
		<cimplement name="com.ntmast.processmanage.ProcessAccessorForDB"/>
	</cinterface>	
	<cinterface name="com.ntmast.commons.util.transaction.XmlWriteTran">
	<!--	<cimplement name="com.ntmast.commons.util.transaction.ProcessManageXmlTransactionForFile"/>-->
		<cimplement name="com.ntmast.commons.util.transaction.ProcessManageXmlTransactionForDb"/>
	</cinterface>
	
</classes>
