=== kelvinBen/ei/WebContent/WEB-INF/classes/dtd/dcworkFormData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://dcworkFromData.config.wf.dcwork.lc.com"
			xmlns="http://dcworkFromData.config.wf.dcwork.lc.com"
			elementFormDefault="qualified">	
    <xsd:element name="forms">
        <xsd:annotation>
        	<xsd:documentation>dcwork自定义的表单集合</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="form" minOccurs="0" maxOccurs="unbounded"/>                          
            </xsd:sequence>               
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="form">
        <xsd:annotation>
        	<xsd:documentation>dcwork自定义的表单数据</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="url" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="buttons" minOccurs="0" maxOccurs="1"/>                
                <xsd:element ref="fields" minOccurs="0"/>                
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:string" use="required"/>
            <xsd:attribute name="name" type="xsd:string" use="required"/>    
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="url">
        <xsd:annotation>
        	<xsd:documentation>获取表单的url</xsd:documentation>
        </xsd:annotation>
    </xsd:element>	
    <xsd:element name="buttons">
      	<xsd:complexType>
         	<xsd:sequence>
            	<xsd:element ref="button" minOccurs="0" maxOccurs="unbounded"/>
         	</xsd:sequence>
      	</xsd:complexType>
    </xsd:element>    
    <xsd:element name="button">
        <xsd:annotation>
        	<xsd:documentation>表单上的操作按扭,readonly-show只读显示按钮(即流程办结后默认显示的按钮),isDefault默认显示按钮</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:attribute name="id" type="xsd:string" use="required"/>
            <xsd:attribute name="name" type="xsd:string" use="required"/>	
			<xsd:attribute name="readonly-show" default="false">
				<xsd:simpleType>
					<xsd:restriction base="xsd:token">
						<xsd:enumeration value="true" />
						<xsd:enumeration value="false" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="isDefault" default="false">
				<xsd:simpleType>
					<xsd:restriction base="xsd:token">
						<xsd:enumeration value="true" />
						<xsd:enumeration value="false" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>						 
			<xsd:attribute name="description" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="fields">
      	<xsd:complexType>
         	<xsd:sequence>
            	<xsd:element ref="field" minOccurs="0" maxOccurs="unbounded"/>
         	</xsd:sequence>
      	</xsd:complexType>
    </xsd:element>    
    <xsd:element name="field">
        <xsd:annotation>
        	<xsd:documentation>表单字段,datatype=数据类型,description字段描述,date-time是日期时间字段(可选),select-field是选择域字段(可选)</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="date-time" minOccurs="0" maxOccurs="1"/>
                <xsd:element ref="select-field" minOccurs="0" maxOccurs="1"/>     
            </xsd:sequence>			
            <xsd:attribute name="id" type="xsd:string" use="required"/>
            <xsd:attribute name="name" type="xsd:string" use="required"/>	
			<xsd:attribute name="datatype" default="String" use="optional">
				<xsd:simpleType>
					<xsd:restriction base="xsd:NMTOKEN">
						<xsd:enumeration value="String" />
						<xsd:enumeration value="Float" />
						<xsd:enumeration value="Long" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="description" type="xsd:string" use="required"/>        
        </xsd:complexType>
    </xsd:element>	
	<xsd:element name="date-time">
		<xsd:annotation>
			<xsd:documentation>时间字段,timestamp只有时间,date只有日期,time日期+时间</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
		<xsd:attribute name="type" default="timestamp">
			<xsd:simpleType>
				<xsd:restriction base="xsd:token">
					<xsd:enumeration value="timestamp" />
					<xsd:enumeration value="date" />
					<xsd:enumeration value="time" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>			
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="select-field">
		<xsd:annotation>
			<xsd:documentation>选择域字段,通过对话框取值.select-url=字段取值url,module-key取值对应的业务模块主键</xsd:documentation>
			<xsd:documentation>module-key取值对应的业务模块主键,即WfDSystemConfig中定义的针对业务模块配置选项的key</xsd:documentation>
		</xsd:annotation>		
		<xsd:complexType>
			<xsd:attribute name="select-url" type="xsd:string" use="optional" />
			<xsd:attribute name="module-key" type="xsd:string" use="optional" />			
		</xsd:complexType>
	</xsd:element>	
</xsd:schema>

=== kelvinBen/ei/src/main/resources/config/dcworkFormData.xml
<?xml version="1.0" encoding="UTF-8"?>
<forms xmlns="http://dcworkFromData.config.wf.dcwork.lc.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://dcworkFromData.config.wf.dcwork.lc.com dcworkFormData.xsd ">
	<form id="example_ccjk" name="出差借款">
		<url>ccjk.cmd</url>
		<buttons>
			<button id="direforward" name="发送" readonly-show="false" isDefault="true" description="直接发送"/>
			<button id="forward" name="发送" readonly-show="false" isDefault="true" description="发送"/>
			<button id="reject" name="驳回" readonly-show="false" isDefault="true" description="驳回"/>
			<button id="transmit" name="转发" readonly-show="false" isDefault="true" description="转发"/>
			<button id="remove" name="删除" readonly-show="false" isDefault="true" description="删除"/>
			<button id="finish" name="结束" readonly-show="false" isDefault="true" description="结束"/>
		</buttons>
    	<fields>
			<field id="jkMoney"  name="借款额"  datatype="String"  description="">
			</field>	
			<field id="userDept" name="申请人部门" datatype="String" description="">
				<select-field select-url="struhelp.cmd?method=getSelectRoot&amp;organType=2&amp;isCheckBox=0&amp;isIncludeSelf=0&amp;isTree=1&amp;rootId=1" module-key="zuzhijigou"/>
			</field>					
		</fields>    		
	</form>
</forms>
