=== kelvinBen/ei/WebContent/WEB-INF/classes/dtd/workflowEvent.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="event">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="send" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="workflow-create" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="workflow-end" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="app-data" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="log" minOccurs="0" maxOccurs="1"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="action">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="condition" />
			</xsd:sequence>
			<xsd:attribute name="class" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="app-data">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" minOccurs="0" ref="action" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="condition">
		<xsd:complexType>
			<xsd:attribute name="type" default="flow-type">
				<xsd:simpleType>
					<xsd:restriction base="xsd:token">
						<xsd:enumeration value="flow-type" />
						<xsd:enumeration value="regex" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="value" type="xsd:string" use="optional" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="log">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" minOccurs="0" ref="action" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="send">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" minOccurs="0" ref="action" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="workflow-end">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" minOccurs="0" ref="action" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="workflow-create">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" minOccurs="0" ref="action" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>	
	
	<xsd:element name="activity-create">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" minOccurs="0" ref="action" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>		
	
	<xsd:element name="activity-end">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" minOccurs="0" ref="action" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>			
</xsd:schema>

=== kelvinBen/ei/src/main/resources/config/workflowEvent.xml
<?xml version="1.0" encoding="UTF-8"?>
<event xsi:noNamespaceSchemaLocation="../dtd/workflowEvent.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<send>
		<action class="">
			<condition type="flow-type" value="" />
		</action>
	</send>
	<workflow-create>
		<action class="">
			<condition type="flow-type" value="EDOC"/>
		</action>
	</workflow-create>
	<workflow-end>
		<!-- <action class="net.mast.workflow.eventListening.PrApplyProcessEndEventListning">
			<condition type="flow-type" value="ProcessType_abf73323e70" />
		</action>
		<action class="net.mast.workflow.eventListening.HeadPrApplyProcessEndEventListning">
			<condition type="flow-type" value="headworkflow" />
		</action> -->
		<action class="">
			<condition type="flow-type" value="" />
		</action>
	</workflow-end>
	<app-data>
	    <action class="">
			<condition type="flow-type" value="" />
		</action>
	</app-data>
	<log>
		<action class="">
			<condition type="flow-type" value="EDOC" />
		</action>	
	</log>
</event>
